# 1단계: 빌드 환경
FROM ubuntu:22.04 AS build-env

# 필수 패키지 설치
RUN apt-get update && apt-get install -y curl git unzip xz-utils libglu1-mesa
RUN git clone https://github.com/flutter/flutter.git -b stable /usr/local/flutter
ENV PATH="/usr/local/flutter/bin:/usr/local/flutter/bin/cache/dart-sdk/bin:${PATH}"

WORKDIR /app
COPY . .

# [중요] Docker Compose로부터 전달받은 빌드 인자 정의
ARG BASE_URL

RUN flutter pub get
# [중요] 빌드 시점에 Dart 환경 변수로 주입
RUN flutter build web --release --dart-define=BASE_URL=$BASE_URL

# 2단계: 실행 환경 (Nginx)
FROM nginx:stable-alpine
COPY --from=build-env /app/build/web /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]